"""add roles and users

Revision ID: 0d16cb694ccf
Revises: 
Create Date: 2023-05-12 14:11:08.204181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d16cb694ccf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_table_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_table_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_table_last_name'), ['last_name'], unique=False)

    op.drop_table('roles table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_table_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_table_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_table_email'))

    op.drop_table('users_table')
    op.drop_table('roles_table')
    # ### end Alembic commands ###
