"""updated foreign key schema

Revision ID: 30114332bd51
Revises: 511cdd35db3c
Create Date: 2023-06-09 11:18:20.427403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30114332bd51'
down_revision = '511cdd35db3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.alter_column('receiver',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sender',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_transactions_table_receiver_accounts_table'), 'accounts_table', ['receiver'], ['account_num'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_table_sender_accounts_table'), 'accounts_table', ['sender'], ['account_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_table_sender_accounts_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_table_receiver_accounts_table'), type_='foreignkey')
        batch_op.alter_column('sender',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiver',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accounts_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'transactions_table', ['account_num'], ['receiver'])
        batch_op.create_foreign_key(None, 'transactions_table', ['account_num'], ['sender'])

    # ### end Alembic commands ###
