"""changed balance to double type

Revision ID: 617d91ff53bc
Revises: ed414da76afe
Create Date: 2023-06-05 18:12:43.364220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617d91ff53bc'
down_revision = 'ed414da76afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_table', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.BIGINT(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_table', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Double(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
