"""changed balance to float type

Revision ID: 760daf9dca92
Revises: d514d7fb65e7
Create Date: 2023-06-05 18:22:25.896016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760daf9dca92'
down_revision = 'd514d7fb65e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_table', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_table', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
