"""test new schema

Revision ID: 77302b50b38e
Revises: d3377807e9d0
Create Date: 2023-06-08 17:21:37.739714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77302b50b38e'
down_revision = 'd3377807e9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_transactions_table_receiver_accounts_table'), 'accounts_table', ['receiver'], ['account_num'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_table_sender_accounts_table'), 'accounts_table', ['sender'], ['account_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_table_sender_accounts_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_table_receiver_accounts_table'), type_='foreignkey')

    # ### end Alembic commands ###
