"""added transaction types

Revision ID: d3377807e9d0
Revises: 97f87728c563
Create Date: 2023-06-06 14:17:36.970305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3377807e9d0'
down_revision = '97f87728c563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_table_name'), ['name'])

    with op.batch_alter_table('transaction_type_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_transaction_type_table_name'), ['name'])

    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_table_transaction_type_id_transaction_type_table'), 'transaction_type_table', ['transaction_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_table_transaction_type_id_transaction_type_table'), type_='foreignkey')
        batch_op.drop_column('transaction_type_id')

    with op.batch_alter_table('transaction_type_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_transaction_type_table_name'), type_='unique')

    with op.batch_alter_table('roles_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_table_name'), type_='unique')

    # ### end Alembic commands ###
