"""added roles to dev_db

Revision ID: d677e360a68f
Revises: f64980b6e9cc
Create Date: 2023-05-21 20:56:45.302170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd677e360a68f'
down_revision = 'f64980b6e9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions_table',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('receiver', sa.BigInteger(), nullable=True),
    sa.Column('sender', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_table_date_time'), ['date_time'], unique=False)

    op.create_table('accounts_table',
    sa.Column('account_num', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_num'], ['transactions_table.receiver'], ),
    sa.ForeignKeyConstraint(['account_num'], ['transactions_table.sender'], ),
    sa.ForeignKeyConstraint(['owner'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('account_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_table')
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_table_date_time'))

    op.drop_table('transactions_table')
    # ### end Alembic commands ###
