"""added accounts

Revision ID: f64980b6e9cc
Revises: c7dab4bef97c
Create Date: 2023-05-17 22:59:15.241217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64980b6e9cc'
down_revision = 'c7dab4bef97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_table',
    sa.Column('account_num', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_num'], ['transactions_table.receiver'], ),
    sa.ForeignKeyConstraint(['account_num'], ['transactions_table.sender'], ),
    sa.ForeignKeyConstraint(['owner'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('account_num')
    )
    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('sender', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_transactions_table_txn_from')
        batch_op.drop_index('ix_transactions_table_txn_to')
        batch_op.create_index(batch_op.f('ix_transactions_table_date_time'), ['date_time'], unique=False)
        batch_op.drop_column('txn_from')
        batch_op.drop_column('txn_to')

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('txns')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('txns', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'transactions_table', ['txns'], ['id'])

    with op.batch_alter_table('transactions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txn_to', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('txn_from', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_transactions_table_date_time'))
        batch_op.create_index('ix_transactions_table_txn_to', ['txn_to'], unique=False)
        batch_op.create_index('ix_transactions_table_txn_from', ['txn_from'], unique=False)
        batch_op.drop_column('date_time')
        batch_op.drop_column('sender')
        batch_op.drop_column('receiver')

    op.drop_table('accounts_table')
    # ### end Alembic commands ###
