# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci-python-unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with unittest
      run: |
        python webapp.py
        flask test > test.log || true
        
    - name: Send mail 
      if: always() 
      uses: dawidd6/action-send-mail@v3 
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # Optional (recommended): mail server username
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password
        password: ${{secrets.MAIL_PASSWORD}}
        # email subject
        subject: Test results on branch ${{ github.ref }}
        # email body as text
        attachments: test.log
        # comma-separated string, send email to
        to: sunsethorizonstories@gmail.com
        # from email name
        from: ${{ github.actor }} <noreply@github.actions.com>

    
